### ISSUE TITLE
对单个词语时的问题

### ISSUE THREAD

**Issue by tespent** [wb14123/seq2seq-couplet#16]
在demo里，有几个词语都被对成了“开发区”
目前我看到的有：
好运气
运动会
大新闻

这是不是一个bug的征兆？

**Comment by computerhost1** [comment]
另：给出“哈哈”居然对出个“嘿嘿嘿”
其他某些词也有时会引起字数增多

**Comment by lonerfscar** [comment]
任天堂也是开发区www

**Comment by LaoshuBaby** [comment]
你们够了！主席的全名打进去也是开发区！
（别问我为啥会脑子抽了敢拿主席名字打进去我不知道）

**Comment by AndyLIUMel** [comment]
我也补充一个， 真香   下联是颠

**Comment by Lightcolour-666** [comment]
我也补充一个 柠檬酸了
