### ISSUE TITLE
对联的平仄关系需要做特殊处理吗？

### ISSUE THREAD

**Issue by jobsjiang** [wb14123/seq2seq-couplet#17]

**Comment by wb14123** [comment]
目前系统只从训练数据来学习平仄规则，没有特殊处理。从结果来看，如果上联符合平仄的话，下联一般都可以对的上。现在有个更大的问题是重字经常对不上，我曾经试着改一下cost函数处理这个问题，但是没有成功

**Comment by jobsjiang** [comment]
好的，谢谢！
