### ISSUE TITLE
上联“哔哩哔哩”，下联只有两个字“非耶”

### ISSUE THREAD

**Issue by lihaoyun6** [wb14123/seq2seq-couplet#18]
如题

**Comment by Bluesn0w** [comment]
我也发现有的时候会少字，研究了下作者的code和训练集，估计因为哔不在vocabs里（我猜vocab是训练集里的unique汉字），所以model不认识这字，所以就直接去掉了，同理很多生僻字也是直接跳过的。

**Comment by wb14123** [comment]
是这个原因
