### ISSUE TITLE
昨晚失眠恰好写了两对

### ISSUE THREAD

**Issue by yyrdl** [wb14123/seq2seq-couplet#2]
上联： 一点青山 二分秋水 藏不住  三里桃花

上联：水映青山山映水

**Comment by yyrdl** [comment]
额，没人对对联感兴趣么？

**Comment by AnyListen** [comment]
第一个 秋水 换成春水 比较好吧

**Comment by yyrdl** [comment]
@AnyListen  哈哈 程序猿的严谨 ， 但没说时间上要合理啊，也可以是一年四季中的景色摘取 ：）

还是我自己对这个吧：

一点青山 二分秋水  藏不住  三里桃花

六朝骈文 七言诗律  表不了  八方绮丽

一二三  六七八 哈哈
另一个：

水映青山山映水  风拂弱柳柳拂风

**Comment by AldrichLeo** [comment]
兄弟你知道如何用customerHelper中不做embedding的写法吗
