### ISSUE TITLE
试试  蔡徐坤鸡你太美 

### ISSUE THREAD

**Issue by Enaium** [wb14123/seq2seq-couplet#32]
上联： 蔡徐坤鸡你太美

**Comment by ASC8384** [comment]
对出了：中华国梦我真圆。。。
还有个，
上联：
`仙人抚我顶`
下联：
`老子出山门`

**Comment by Luciohavenomoney** [comment]
小女喧嚣，问闺中何事，只因鸡你太美
大师摇落，看世上哪班，全仗李学才高

**Comment by jadeStoneStonger** [comment]
烟沿艳檐掩燕眼

对曰：

风搓翠柳舞蝶衣

什么鬼

**Comment by SeakyLuo** [comment]
@jadeStoneStonger 人家又不考虑发音的

**Comment by caddyless** [comment]
![Uploading image.png…]()
这发音对得好啊
