### ISSUE TITLE
收敛了www

### ISSUE THREAD

**Issue by yys-github** [wb14123/seq2seq-couplet#37]
上联：
一枕松风声更幽
下联：
半窗竹影韵尤幽
下联：
一枕松风声更幽
下联：
半窗竹影韵尤幽
（无限循环）

**Comment by yys-github** [comment]
世事千般难免提<-----
人情二味不如初
世事三千莫若无
人情万两岂如同
世事千般不胜悲
人情万象更如何
世事千般难免提<----

（我真是闲的蛋疼23333

**Comment by FengGuanxi** [comment]
朋友能提供一下训练好的模型么

**Comment by wb14123** [comment]
恭喜。正常来说，上联需要符合平仄规则，最后一个字需要是仄声。第一个例子中末字幽是平声，所以下联效果不会很好
