### ISSUE TITLE
网站证书过期了

### ISSUE THREAD

**Issue by 01010101lzy** [wb14123/seq2seq-couplet#38]
![image](https://user-images.githubusercontent.com/10259119/65399337-ab746e00-ddee-11e9-98f7-52b62953f2b5.png)

如图。如果选择忽略并打开网页话请求也会因为证书过期无法加载。

![image](https://user-images.githubusercontent.com/10259119/65399364-cc3cc380-ddee-11e9-86be-0cbcfc2ba1bb.png)

**Comment by wb14123** [comment]
多谢提醒，已经修复
