### ISSUE TITLE
真的好厉害！

### ISSUE THREAD

**Issue by LRQLRQ** [wb14123/seq2seq-couplet#44]
今天偶然间知乎推送了这个项目，打开看了下真有意思。试了一下这个对联的接口，发现主页面还是nginx的欢迎界面，哈哈！  

---

#### 深度学习模型怎么跑在后端提供接口
有点好奇深度学习跑出来的模型，怎么运行产生后端接口来访问？是怎么的一套流程呢？老哥有空的时候方便说下？   
#### 想借你的接口用在自己的应用
我想在自己的小项目网站加上这个对对联的功能，不会有多少访问量，纯属自娱自乐。   
要是兄弟你觉得不行，跟我说下我随时撤掉。   
最后膜拜大佬！

**Comment by z-t-y** [comment]
我的想法是：先调用深度学习里的某个函数获得返回值并存储再变量中（原谅我还没看过源代码），  
再用Flask或Django对Jinja2模板进行渲染输出到网页。

**Comment by wb14123** [comment]
`server.py` 就是对应的后端 API 代码。使用 Flask 接受请求并且调用模型进行推断。
