### ISSUE TITLE
对繁体字的识别成迷

### ISSUE THREAD

**Issue by chenryn** [wb14123/seq2seq-couplet#48]
不小心贴了一句繁体字，然后发现行为很迷啊。

1. 學士衣冠無彩色 -> 文章黼黻芳名
2. 學士衣冠无彩色 -> 人面壁有光辉
3. 学士衣冠無彩色 -> 先生仪表聿元辉
4. 学士衣冠无彩色 -> 英雄肝胆有余香

**Comment by wb14123** [comment]
训练样本中并没有繁体字，所以模型也不支持繁体字。在界面中已有相关提示。
