### ISSUE TITLE
三观很正

### ISSUE THREAD

**Issue by tylk520** [wb14123/seq2seq-couplet#56]
上联：
日本
下联：
天灾

**Comment by tylk520** [comment]
上联：
天生一个仙人洞
下联：
地造千秋帝子宫

**Comment by tylk520** [comment]
上联：
江山如此多娇，引无数英雄竞折腰。
下联：
风景这边独好，愿多少儿女莫负心田

为何多一个字

**Comment by z-t-y** [comment]
还有：
上联：  
奥巴马
下联：
翘尾猴

**Comment by karanocave** [comment]
特朗普
黄据多

**Comment by ixing7** [comment]
上联：
一人一坐一电脑
下联：
二奶三陪俩二爷
