### ISSUE TITLE
What are these???

### ISSUE THREAD

**Issue by z-t-y** [wb14123/seq2seq-couplet#60]
![image](https://user-images.githubusercontent.com/44891657/81377745-af17f380-9138-11ea-8a5f-184ec0f72d16.png)
![image](https://user-images.githubusercontent.com/44891657/81377800-c9ea6800-9138-11ea-8e31-4457a6cf8608.png)
![image](https://user-images.githubusercontent.com/44891657/81377921-fdc58d80-9138-11ea-8d87-27faa0f0369f.png)
### 三观太正了
😂😂😂

**Comment by zbwxtex** [comment]
绝了

**Comment by z-t-y** [comment]
![image](https://user-images.githubusercontent.com/44891657/81390788-a03c3b80-914e-11ea-9e7f-f160dd7e4356.png)
![image](https://user-images.githubusercontent.com/44891657/81390791-a0d4d200-914e-11ea-864d-7848320b4c00.png)
![image](https://user-images.githubusercontent.com/44891657/81390790-a0d4d200-914e-11ea-9cf1-4fc47eeb11a5.png)

**Comment by z-t-y** [comment]
还有：
![image](https://user-images.githubusercontent.com/44891657/81391015-0032e200-914f-11ea-9b9e-3bd7e15221d6.png)

**Comment by z-t-y** [comment]
![image](https://user-images.githubusercontent.com/44891657/81670711-98e09f00-947a-11ea-81fa-e9c929dcc6c6.png)
这AI都这么黄了？

**Comment by Ycchery** [comment]
绝了
