### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/data/dl-data/couplet/vocabs'

### ISSUE THREAD

**Issue by oklare** [wb14123/seq2seq-couplet#72]
如题，为啥我把couplet放进去（https://github.com/wb14123/couplet-dataset/releases/download/1.0/couplet.tar.gz ），报这个错误呢， FileNotFoundError: [Errno 2] No such file or directory: '/data/dl-data/couplet/vocabs'

**Comment by liuhui0401** [comment]
First, you need to download the dataset following the readme file. Second, you should set the path in couplet.py to your own storage path.

**Comment by liuhui0401** [comment]
@oklare  First, you need to download the dataset following the readme file. Second, you should set the path in couplet.py to your own storage path.
