### ISSUE TITLE
😱

### ISSUE THREAD

**Issue by Cicada000** [wb14123/seq2seq-couplet#73]
![IMG_20220129_202840_152](https://user-images.githubusercontent.com/78632923/151661224-2d72f492-4432-4e3e-808d-96b1914dcd53.jpg)

**Comment by Cicada000** [comment]
试了一下还是真的

**Comment by Lijiaxing-lx** [comment]
您好，邮件已收到。我将尽快给你回复。

**Comment by zhoujinyang1996** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Murasame0721** [comment]
woc
