### ISSUE TITLE
这个还是挺难的吧,工整吗？可以作为样本吧

### ISSUE THREAD

**Issue by zoyanhui** [wb14123/seq2seq-couplet#74]
![image](https://user-images.githubusercontent.com/7187955/160052169-6ca7c397-33b2-4ca5-a8e5-e288036c3186.png)

虎头虎脑虎年虎虎生威
->
山欢水笑迎春山山呈祥

**Comment by zhoujinyang1996** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Lijiaxing-lx** [comment]
您好，邮件已收到。我将尽快给你回复。
