### ISSUE TITLE
草！太有节目效果了！

### ISSUE THREAD

**Issue by Lu-Qi-777** [wb14123/seq2seq-couplet#79]
（我知道是安倍啦！
![image](https://user-images.githubusercontent.com/21366357/177920532-de126ad2-298f-41ae-9196-b2da127a8758.png)
![image](https://user-images.githubusercontent.com/21366357/177920562-6ef800b0-4c91-4ddd-9191-550c2458f563.png)

**Comment by Lijiaxing-lx** [comment]
您好，邮件已收到。我将尽快给你回复。

**Comment by zhoujinyang1996** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by AntonVanke** [comment]
安培是谁
